{{- if and (not .Values.postgres.isExternal) (eq .Values.status "Stopped") .Values.runPostgresMigration }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: pvc
  name: {{ .Release.Name }}-blackduck-postgres-upgrader
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.claimSize }}
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass }}
  {{- else if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end}}
  {{- if .Values.postgres.volumeName }}
  volumeName: {{ .Values.postgres.volumeName }}
  {{- end -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: postgres-upgrader
  name: {{ .Release.Name }}-blackduck-postgres-upgrader
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: postgres-upgrader
      annotations:
        checksum/postgres-config: {{ include (print $.Template.BasePath "/postgres-config.yaml") . | sha256sum }}
      name: {{ .Release.Name }}-blackduck-postgres-upgrader
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-blackduck-db-config
          - configMapRef:
              name: {{ .Release.Name }}-blackduck-config
          {{- if .Values.postgresUpgrader.registry }}
            {{- if .Values.postgresUpgrader.imageTag }}
          image: {{ .Values.postgresUpgrader.registry }}/blackduck-postgres-upgrader:{{ .Values.postgresUpgrader.imageTag }}
            {{- else }}
          image: {{ .Values.postgresUpgrader.registry }}/blackduck-postgres-upgrader:{{ .Values.imageTag }}
            {{- end}}
          {{- else }}
            {{- if .Values.postgresUpgrader.imageTag }}
          image: {{ .Values.registry }}/blackduck-postgres-upgrader:{{ .Values.postgresUpgrader.imageTag }}
            {{- else }}
          image: {{ .Values.registry }}/blackduck-postgres-upgrader:{{ .Values.imageTag }}
            {{- end}}
          {{- end}}
          {{- include "customImagePullPolicy" .Values.postgresUpgrader | nindent 10 }}
          name: {{ .Release.Name }}-blackduck-postgres-upgrader
          resources:
            {{- toYaml .Values.postgresUpgrader.resources | nindent 14 }}
          {{- with .Values.postgresUpgrader.securityContext }}
          securityContext: {{ toJson . }}
          {{- end }}
          volumeMounts:
          - mountPath: /bitnami/postgresql
            name: postgres-data-volume
      {{- include "bd.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.postgres.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.postgres.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.postgres.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- if .Values.postgresUpgrader.podSecurityContext }}
      {{- with .Values.postgresUpgrader.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- else }}
      {{- include "bd.podSecurityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-blackduck-service-account
      restartPolicy: Never
      volumes:
      {{- include "postgresUpgraderPersistentStorage" . | nindent 6 }}
{{- end }}

{{- define "postgresUpgraderPersistentStorage" -}}
{{- if and (not .Values.postgres.isExternal) (eq .Values.status "Stopped") .Values.runPostgresMigration .Values.enablePersistentStorage -}}
- name: postgres-data-volume
  persistentVolumeClaim:
    claimName: {{if .Values.postgres.persistentVolumeClaimName}} {{.Values.postgres.persistentVolumeClaimName}} {{else}} {{ .Release.Name }}-blackduck-postgres {{end}}
{{- else -}}
- emptyDir: {}
  name: postgres-data-volume
{{- end -}}
{{- end -}}
