apiVersion: v1
data:
  SEAL_KEY: {{ .Values.sealKey | b64enc }}
kind: Secret
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: uploadcache
  name: {{ .Release.Name }}-blackduck-upload-cache
  namespace: {{ .Release.Namespace }}
type: Opaque