environs:
  MAX_CONCURRENT_JOBS: "4"
  SCANNER_CONCURRENCY: "1"
  BLACKDUCK_HUB_DB_POOL_MAX_ACTIVE: "32"
  BLACKDUCK_REDIS_MAXMEMORY: "31335mb"

authentication:
  replicas: 1
  hubMaxMemory: "1844m"
  resources:
    limits:
      cpu: "700m"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "2048Mi"

bomengine:
  replicas: 4
  hubMaxMemory: "4148m"
  resources:
    limits:
      cpu: "1000m"
      memory: "4608Mi"
    requests:
      cpu: "700m"
      memory: "4608Mi"

cfssl:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "300m"
      memory: "1024Mi"

documentation:
  replicas: 1
  hubMaxMemory: "1383m"
  resources:
    limits:
      cpu: "500m"
      memory: "1536Mi"
    requests:
      cpu: "300m"
      memory: "1536Mi"

jobrunner:
  replicas: 4
  hubMaxMemory: "5807m"
  resources:
    limits:
      cpu: "1500m"
      memory: "6451Mi"
    requests:
      cpu: "1000m"
      memory: "6451Mi"

logstash:
  replicas: 1
  hubMaxMemory: "3687m"
  resources:
    limits:
      cpu: "1000m"
      memory: "4096Mi"
    requests:
      cpu: "700m"
      memory: "4096Mi"

matchengine:
  replicas: 12
  hubMaxMemory: "9216m"
  resources:
    limits:
      cpu: "1000m"
      memory: "10240Mi"
    requests:
      cpu: "700m"
      memory: "10240Mi"

postgres:
  replicas: 1
  resources:
    limits:
      cpu: "18000m"
      memory: "64Gi"
    requests:
      cpu: "9000m"
      memory: "64Gi"

postgresUpgrader:
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"

postgresWaiter:
  resources:
    limits:
      cpu: "250m"
      memory: "500Mi"
    requests:
      cpu: "250m"
      memory: "500Mi"

rabbitmq:
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "1433Mi"

redis:
  replicas: 1
  resources:
    limits:
      cpu: "1200m"
      memory: "34816Mi"
    requests:
      cpu: "500m"
      memory: "5120Mi"

registration:
  replicas: 1
  hubMaxMemory: "2765m"
  resources:
    limits:
      cpu: "700m"
      memory: "3072Mi"
    requests:
      cpu: "500m"
      memory: "3072Mi"

scan:
  replicas: 12
  hubMaxMemory: "13824m"
  resources:
    limits:
      cpu: "1000m"
      memory: "15360Mi"
    requests:
      cpu: "700m"
      memory: "15360Mi"

uploadcache:
  replicas: 1
  resources:
    limits:
      cpu: "600m"
      memory: "1536Mi"
    requests:
      cpu: "300m"
      memory: "1024Mi"

webapp:
  replicas: 1
  hubMaxMemory: "13824m"
  resources:
    limits:
      cpu: "5000m"
      memory: "15360Mi"
    requests:
      cpu: "3000m"
      memory: "15360Mi"

webserver:
  replicas: 1
  resources:
    limits:
      cpu: "600m"
      memory: "2048Mi"
    requests:
      cpu: "400m"
      memory: "1024Mi"

webui:
  replicas: 1
  resources:
    limits:
      cpu: "600m"
      memory: "1536Mi"
    requests:
      cpu: "300m"
      memory: "1024Mi"
