environs:
  BLACKDUCK_DEPLOYMENT_BASE_SIZE: "sizes-gen01/legacy-x-large.yaml"

postgres:
  resources:
    requests:
      cpu: "3000m"
      memory: "12288Mi"

jobrunner:
  replicas: 10
  hubMaxMemory: "12288m"
  maxPeriodicThreads: 8
  maxPeriodicPrefetch: 4
  maxOndemandThreads: 24
  maxOndemandPrefetch: 16
  resources:
    limits:
      cpu: "1000m"
      memory: "13824Mi"

scan:
  replicas: 5
  hubMaxMemory: "8192m"
  resources:
    limits:
      memory: "9728Mi"

storage:
  replicas: 1
  hubMaxMemory: "1024m"
  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"
    requests:
      cpu: "700m"
      memory: "2048Mi"

webapp:
  hubMaxMemory: "18192m"
  resources:
    requests:
      cpu: "3000m"
    limits:
      memory: "19728Mi"

webserver:
  resources:
    limits:
      memory: "2048Mi"

webui:
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

bomengine:
  replicas: 6
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
    limits:
      memory: "13824Mi"

matchengine:
  replicas: 5
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
      cpu: "500m"
    limits:
      memory: "13824Mi"
      cpu: "1000m"
